feat: build and publish snapshots
* split workflows and allow the publishing of snapshots from next-minor and next-major on push

diff --git a/.github/workflows/build-and-release-artifacts.yml b/.github/workflows/build-and-release-artifacts.yml
--- a/.github/workflows/build-and-release-artifacts.yml
+++ b/.github/workflows/build-and-release-artifacts.yml
@@ -1,113 +1,45 @@
 name: Build and Publish Artifacts
 on:
-  push:
-    branches:
-      - "release/*"
+    push:
+        branches:
+            - "next-minor"
+            - "next-major"
+            - "release/*"
 env:
-  NODE_VERSION: "18.x"
+    NODE_VERSION: "20.x"
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Generate github app token
-        id: generate_token
-        uses: actions/create-github-app-token@v1
+    detect-variables:
+        runs-on: ubuntu-latest
+        outputs:
+            scope: ${{ steps.detect-scope.outputs.SCOPE }}
+        steps:
+            -   name: Detect scope
+                id: detect-scope
+                run: echo "SCOPE=$(if ${{ github.ref_name == 'next-minor' || github.ref_name == 'next-major' }} ; then echo "SNAPSHOT" ; elif ${{ startsWith(github.ref-name, 'release/') }} ; then echo "RELEASE" ; else echo "UNKNOWN" ; fi)" >> $GITHUB_OUTPUT
+            -   name: Log scope
+                run: echo "::notice::Using scope - \"${{ steps.detect-scope.outputs.SCOPE }}\"."
+    publish-snapshot:
+        needs:
+            - detect-variables
+        if: ${{ needs.detect-variables.outputs.scope == 'SNAPSHOT' }}
+        uses: ./.github/workflows/publish-snapshot.yml
         with:
-          app-id: ${{ secrets.APP_ID }}
-          private-key: ${{ secrets.APP_PRIVATE_KEY }}
-      - uses: actions/checkout@v4
+            nodeVersion: ${{ env.NODE_VERSION }}
+            targets: "['npm']"
+        secrets: inherit
+    publish-release:
+        needs:
+            - detect-variables
+        if: ${{ needs.detect-variables.outputs.scope == 'RELEASE' }}
+        uses: ./.github/workflows/publish-release.yml
         with:
-          token: ${{ steps.generate_token.outputs.token }}
-      - name: Set up Node.js ${{ env.NODE_VERSION }}
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ env.NODE_VERSION }}
-      - name: Install
-        run: npm install -g pnpm lerna@7.4.2 && pnpm install
-      - name: Build
-        run: pnpm build
-      - name: Test
-        run: pnpm test
-      - name: "Retain build artifact: api"
-        uses: actions/upload-artifact@v4
-        with:
-          name: nl-portal-api
-          path: packages/api/dist/
-          retention-days: 1
-      - name: "Retain build artifact: authentication"
-        uses: actions/upload-artifact@v4
-        with:
-          name: nl-portal-authentication
-          path: packages/authentication/dist/
-          retention-days: 1
-      - name: "Retain build artifact: localization"
-        uses: actions/upload-artifact@v4
-        with:
-          name: nl-portal-localization
-          path: packages/localization/dist/
-          retention-days: 1
-      - name: "Retain build artifact: user interface"
-        uses: actions/upload-artifact@v4
-        with:
-          name: nl-portal-user-interface
-          path: packages/user-interface/dist/
-          retention-days: 1
-  publish-npm:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: Generate github app token
-        id: generate_token
-        uses: actions/create-github-app-token@v1
-        with:
-          app-id: ${{ secrets.APP_ID }}
-          private-key: ${{ secrets.APP_PRIVATE_KEY }}
-      - uses: actions/checkout@v4
-        with:
-          token: ${{ steps.generate_token.outputs.token }}
-      - name: Set up Node.js ${{ env.NODE_VERSION }}
-        uses: actions/setup-node@v4
-        with:
-          node-version: ${{ env.NODE_VERSION }}
-      - name: Install
-        run: |
-          npm install -g pnpm
-          npm install -g lerna@7.4.2
-      - name: "Restore build artifact: api"
-        uses: actions/download-artifact@v4
-        with:
-          name: nl-portal-api
-          path: packages/api/dist/
-      - name: "Restore build artifact: authentication"
-        uses: actions/download-artifact@v4
-        with:
-          name: nl-portal-authentication
-          path: packages/authentication/dist/
-      - name: "Restore build artifact: localization"
-        uses: actions/download-artifact@v4
-        with:
-          name: nl-portal-localization
-          path: packages/localization/dist/
-      - name: "Restore build artifact: user interface"
-        uses: actions/download-artifact@v4
-        with:
-          name: nl-portal-user-interface
-          path: packages/user-interface/dist/
-      - name: lerna version
-        env:
-          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
-          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
-          GIT_AUTHOR_NAME: "nl-portal"
-          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
-          GIT_COMMITTER_NAME: "nl-portal"
-        run: |
-          git push --set-upstream origin HEAD
-          pnpm run release --yes
-      - name: lerna publish
-        env:
-          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
-        run: |
-          npm config set "//registry.npmjs.org/:_authToken" "${NPM_ACCESS_TOKEN}"
-          npm config set access public
-          npm run publish -- --no-verify-access --yes
-          npm config delete "//registry.npmjs.org/:_authToken"
+            nodeVersion: ${{ env.NODE_VERSION }}
+        secrets: inherit
+    unknown-scope:
+        needs:
+            - detect-variables
+        if: ${{ needs.detect-variables.outputs.scope == 'UNKNOWN' }}
+        runs-on: ubuntu-latest
+        steps:
+            -   name: Fail on invalid scope
+                run: echo "::error::Failed to detect scope for this branch. Please make sure this workflow is ran against the correct branches."  && exit 1
